# Generated by Django 4.1 on 2023-06-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'contacto', 'verbose_name_plural': 'contactos'},
        ),
        migrations.AlterModelTable(
            name='contacto',
            table='demo_contacto',
        ),
    ]
