# Generated by Django 4.1 on 2023-06-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_alter_contacto_options_alter_contacto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='contenido',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
