# Generated by Django 4.1 on 2023-07-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Disponibilidad',
            new_name='disponibilidad',
        ),
    ]
