# Generated by Django 4.1 on 2023-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_precio_alter_producto_precio_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_currency',
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
