# Generated by Django 4.1 on 2023-06-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(help_text='Test Help', upload_to='img'),
        ),
    ]
